from __future__ import annotations

class PipelineError(Exception):
    def __init__(self, message: str, *, cause: Exception | None = None):
        super().__init__(message)
        self.cause = cause

class DbError(PipelineError): ...
class BudgetError(PipelineError): ...
class LlmClientError(PipelineError): ...
class ValidationError(PipelineError): ...
class IoError(PipelineError): ...
