#config/normalize.yml
# Normalization configuration (consumed by loader.py). No code defaults.

# "preserve" | "lf" | "crlf"
newline_policy: "preserve"

# File encoding used when writing generated artifacts
encoding: "utf-8"

# Whether to strip trailing whitespace from lines
strip_trailing_ws: false

# Paths to exclude from normalization (globs; loader normalizes separators)
excluded_paths: []
