#config/spine.yml
# Centralized Spine configuration (fail-fast; consumed by loader.py).
# All paths are relative to the 'config' directory unless absolute.

caps_path: "spine/capabilities.yml"

pipelines_root: "spine/pipelines"

# Active pipeline profile (must exist as a subdirectory under pipelines_root)
profile: "default"

# Middlewares injected into the Spine registry in order (optional).
# Each entry is "module:function". Leave empty to disable.
middlewares: []
